### ISSUE TITLE
list_blobs_segmented is not returning directories hierarchically

### ISSUE THREAD

**Issue by NaraVen** [Azure/azure-storage-cpplite#105]
We are calling list_blobs_segmented from blob_client, we get en-GUIB, en_HI and then en. Shouldn't directory en be returned first?
See below, we get the following error if we ask for only 2 results (en is the third)
drwxrwxrwx 2 azureuser azureuser 4096 Jan  1  1970 ca
drwxrwxrwx 2 azureuser azureuser 4096 Jan  1  1970 ch
d????????? ? ?         ?            ?            ? codeswitch
drwxrwxrwx 2 azureuser azureuser 4096 Jan  1  1970 cs
drwxrwxrwx 2 azureuser azureuser 4096 Jan  1  1970 da
drwxrwxrwx 2 azureuser azureuser 4096 Jan  1  1970 de
drwxrwxrwx 2 azureuser azureuser 4096 Jan  1  1970 el
**d????????? ? ?         ?            ?            ? en
drwxrwxrwx 2 azureuser azureuser 4096 Jan  1  1970 en-GBAU
drwxrwxrwx 2 azureuser azureuser 4096 Jan  1  1970 en-IN**

**Comment by Jinming-Hu** [comment]
Hi @NaraVen , can you give us a code snippet to reproduce this issue?

Here's a program I used to test

```
std::string continuation_token;
do
{
  auto list_result = client.list_blobs_segmented(container_name, std::string(), continuation_token, std::string(), 2).get();
  if (!list_result.success())
  {
    std::cout << "error" << std::endl;
    break;
  }
  continuation_token = list_result.response().next_marker;
  for (auto b : list_result.response().blobs)
  {
    std::cout << b.name << std::endl;
  }
} while (!continuation_token.empty());
```

The result is

```
en
en-GBAU
en-IN
```

in [this](https://docs.microsoft.com/en-us/rest/api/storageservices/list-blobs) API reference, it says `Blobs are listed in alphabetical order in the response body, with upper-case letters listed first.`. it works exactly as expected.

**Comment by NaraVen** [comment]
Hi Jinming,
     I see the opposite order. The storage container I am testing it is in Central US and has 500 petabytes of data. Could that be the reason?
list_segmented_item do loop blob prefix: am_data/en continuation: 2!76!MDAwMDExIWFtX2RhdGEvZW4wITAwMDAyOCE5OTk5LTEyLTMxVDIzOjU5OjU5Ljk5OTk5OTlaIQ--
Sep 26 22:02:20 naraPhilygpu blobfuse[53016]: Function azs_getattr, in file /home/azureuser/azure-storage-fuse/blobfuse/utilities.cpp, line 254: In azs_getattr list_segmented_item 0 file am_data/en-GBAU/
Sep 26 22:02:20 naraPhilygpu blobfuse[53016]: Function azs_getattr, in file /home/azureuser/azure-storage-fuse/blobfuse/utilities.cpp, line 254: In azs_getattr list_segmented_item 1 file am_data/en-IN/
Sep 26 22:02:20 naraPhilygpu blobfuse[53016]: Function azs_getattr, in file /home/azureuser/azure-storage-fuse/blobfuse/utilities.cpp, line 254: In azs_getattr list_segmented_item 2 file am_data/en/

You can ping me at narven@microsoft.com<mailto:narven@micvrosoft.com> if you want to see this test.
Nara

**Comment by Jinming-Hu** [comment]
Hi @NaraVen , cpplite sdk doesn't sort the result at all, it simply returns what storage server returns.

I just talked with some guy who's familiar with server side implementation. Since Blob service doesn't have real directory, it only has **virtual** directory. Storage server stores every blobs under the directory except the directory itself. For example, in your case you have directory `en-IN` and blob `en-IN/a` and directory `en` and blob `en/b`. Storage server only stores

```
en-IN/a
en/b
```

So when you list directories, the `/` also counts and `en/` comes after `en-IN/`. This is by design.

**Comment by NaraVen** [comment]
Nice and detailed explanation, Thanks, closing the issue.
