### ISSUE TITLE
Comparison to azure-storage-fuse/azure-storage-cpp-lite

### ISSUE THREAD

**Issue by damienpontifex** [Azure/azure-storage-cpplite#13]
Came across this and was wondering what the difference here is to the source at https://github.com/Azure/azure-storage-fuse/tree/master/azure-storage-cpp-lite ?

I am depending on the storage library source there for an implementation of azure blob support in an upcoming tensorflow/io PR. On the surface it seems like this has been extracted from that original repo and I'd prefer to target this dedicated repo if it's going to stick around as a c++ storage library.

Does this seem appropriate to move the dependency from azure-storage-fuse/azure-storage-cpp-lite source to this?

**Comment by katmsft** [comment]
Currently we do not have a plan of maintaining azure-storage-fuse/azure-storage-cpp-lite. If you are purely depending on a C++ client library for Azure Storage services, I would strongly recommend you use this library instead. As you can see from the PR history, this repository will be better maintained for this purpose.

**Comment by damienpontifex** [comment]
Thank you @katmsft. Succinct and exactly what I needed to know 😄
