### ISSUE TITLE
Move to 'modern' cmake?

### ISSUE THREAD

**Issue by damienpontifex** [Azure/azure-storage-cpplite#27]
Are there current blockers to updating the minimum cmake version to 3.x? 

It's something I'm interested in and a lot of nice features in 3.x with target specific setup and additions that could be made to make it easier to integrate this library into another project.

**Comment by katmsft** [comment]
Can we actually add something like 'if (VERSION GREATER 3.0)' for the features you wanted to have in the cmake file rather than making it a requirement to provide backward compatibility? There is currently no data on our end to support that there isn't many users that are currently using cmake 2.8~3.0 to consume this repository.

**Comment by damienpontifex** [comment]
That greater than check can be added. It's the niceties that might simplify things that I'd like to add such as `target_compile_features(myTarget PUBLIC cxx_std_11)` vs providing compiler specific arguments.

I don't know of a way to get usage stats on that. I assume generally it's versions that are provided as defaults on linux LTS releases that defines what users might have available.

**Comment by damienpontifex** [comment]
I was looking into this for another project and we went on Ubuntu LTS release versions. With 14.04 end of life was April this year, then 16.04 is the oldest LTS we thought as a good starting target. It had cmake 3.5.1 as its default https://launchpad.net/ubuntu/xenial/+source/cmake

@katmsft pending no other usage stats what are your thoughts on this conclusion for which cmake version to minimum target?

**Comment by JinmingHu-MSFT** [comment]
@damienpontifex Hi, We just raised the minimum required CMake version to 3.6.
