### ISSUE TITLE
Using CNG for hashing on windows

### ISSUE THREAD

**Issue by raghujayan** [Azure/azure-storage-cpplite#44]
Seems like the only need for OpenSSL on windows is for hashing when using SharedKeys.

Why can't we use Windows CNG (bcrypt) for doing this. This removes the dependency on OpenSSL. 

I could update CmakeList.txt and hash.cpp to fix this. What do you guys think?

P.S: This could be considered an extension to the previous issue reported in using SChannel (WinSSL) #42 on windows for TLS. If  this is adopted then there is no need to carry the OpenSSL dependency around for the main sdk

**Comment by JinmingHu-MSFT** [comment]
@raghujayan Yes, this is feasible. Any contribution is welcomed.

**Comment by JinmingHu-MSFT** [comment]
@raghujayan This is done. See it here https://github.com/Azure/azure-storage-cpplite/pull/41/commits/a530eda030405ae7ab358df24f0f9de04fd848af

**Comment by raghujayan** [comment]
Thank you adding this feature @JinmingHu-MSFT .
