### ISSUE TITLE
put_blob loses errors

### ISSUE THREAD

**Issue by jking777** [Azure/azure-storage-cpplite#47]
`blob_client_wrapper::put_blob` may lose error codes from its call to `m_blobClient->upload_block_blob_from_stream`. If that call results in an error then `errno` is set to the value of the HTTP error code, for example 403. Then `put_blob` closes the input stream, which will reset `errno` to 0. The caller of `blob_client_wrapper::put_blob` then has no indication that the upload failed.

**Comment by JinmingHu-MSFT** [comment]
I'll take time to look into this issue.

**Comment by JinmingHu-MSFT** [comment]
This should have been fixed in this commit https://github.com/Azure/azure-storage-cpplite/commit/c771d89e8493906b94390d082d714754ac75bcff.

**Comment by jking777** [comment]
Thank you!
