### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by raghujayan** [Azure/azure-storage-cpplite#52]
Will there be a new release of the SDK soon? We would like to integrate into our CI/CD and want tie to a specific version.

Given then we would need the new features that you have in place, I was hoping you could cut a new release. 

Thank you,

**Comment by JinmingHu-MSFT** [comment]
Hi @raghujayan , we're planning a new release early January, are you okay with that?

**Comment by raghujayan** [comment]
That will work. Thank you @JinmingHu-MSFT
