### ISSUE TITLE
Client request id

### ISSUE THREAD

**Issue by raghujayan** [Azure/azure-storage-cpplite#53]
How does one provide client request id header ( x-ms-client-request-id )? I know it is optional but would like to know how do applications generate it/provide it and how do I use it with the SDK?

Thank you
~Raghu

**Comment by katmsft** [comment]
Currently there is no support of client request ID header.
Are you asking for auto generated UUID as a default client request ID or if you want customization of client request ID that can be set at runtime?

**Comment by raghujayan** [comment]
@katmsft  We do not have a specific use case as of now. But while working with Azurite (Azure storage server clone) Service we encountered this header. 

I more curious as to how this header is used in general and how it would be generated if we used azure storage cpplite.

Thank you,
Raghu

**Comment by JinmingHu-MSFT** [comment]
@raghujayan It's pretty much just a unique identifier of a request, mostly used for debug purpose as far as I know. You can use any random string. The sdk usually generates a UUID for each request.

**Comment by raghujayan** [comment]
@JinmingHu-MSFT Thank you

**Comment by JinmingHu-MSFT** [comment]
@raghujayan Hi, I noticed you closed this issue. Since this feature isn't implemented yet, does it mean you no longer request for this feature?
