### ISSUE TITLE
Crash occurs with container_exists & get_blob_property with invalid credentails

### ISSUE THREAD

**Issue by prasanthrgb** [Azure/azure-storage-cpplite#65]
Hello All,

I am just trying to create IoT application with Azure. I am using Blob storage sdk lite and facing some issues as below:
The code at line 4 and 5 sometimes get into infinite loop or crashes (some times) If invalid credential is passed to account.
1. auto bC = std::make_shared<blob_client>(account, 10);
2. bool exists = true;
3. blob_client_wrapper bc(bC);
4. exists = bc.container_exists(strContainerName);
5. get_blob_property

Is there any way to check if valid or any fix available for this?

**Comment by JinmingHu-MSFT** [comment]
@prasanthrgb Please change the value [here](https://github.com/Azure/azure-storage-cpplite/blob/12766488a7f8f22b53e2c97da77caad8a2f038d1/include/retry.h#L87) from `26` to smaller value like `3` and try again. Thanks

**Comment by prasanthrgb** [comment]
Thank you. Your suggestion works so that API does not hangs.
